#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef TRUVIDEOSDKCAMERA_SWIFT_H
#define TRUVIDEOSDKCAMERA_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TruvideoSdkCamera",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)




























/// A registry for the TruVideo SDK Camera library that provides library metadata and configuration.
SWIFT_CLASS("_TtC17TruvideoSdkCamera16SDKCameraLibrary")
@interface SDKCameraLibrary : NSObject
/// Registers the camera library with the SDK’s library registry.
/// This static method registers the camera library instance with the global
/// library registry system. It should be called during SDK initialization
/// to ensure the camera library is properly registered and available for
/// dependency injection and service discovery.
+ (void)register;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum TruvideoSdkCameraFlashMode : NSInteger;
@class TruvideoSdkCameraMediaMode;
enum TruvideoSdkCameraOrientation : NSInteger;

/// A configuration object for setting up the AR Camera in <code>TruvideoSdkCamera</code>.
/// <code>TruvideoSdkARCameraConfiguration</code> allows you to customize the AR Camera’s behavior, including flash settings, capture mode,
/// and camera orientation.
/// <h2>Example Usage</h2>
/// \code
/// let arConfig = TruvideoSdkARCameraConfiguration(
///     flashMode: .auto,
///     mode: .videoAndPicture(videoMaxCount: 3, pictureMaxCount: 5, durationLimit: 15),
///     orientation: .portrait
/// )
///
/// \endcodeThis configuration can be passed to <code>presentTruvideoSdkARCameraView</code> to launch the AR Camera with the specified settings.
/// <h2>See Also</h2>
/// <ul>
///   <li>
///     <code>TruvideoSdkCameraFlashMode</code>
///   </li>
///   <li>
///     <code>TruvideoSdkCameraMediaMode</code>
///   </li>
///   <li>
///     <code>TruvideoSdkCameraOrientation</code>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC17TruvideoSdkCamera32TruvideoSdkARCameraConfiguration")
@interface TruvideoSdkARCameraConfiguration : NSObject
/// The flash mode setting for the AR Camera.
/// Determines whether the flash is on, off, or set to auto mode.
@property (nonatomic, readonly) enum TruvideoSdkCameraFlashMode flashMode;
/// The media capture mode for the AR Camera.
/// Defines whether the camera captures photos, videos, or both.
@property (nonatomic, readonly, strong) TruvideoSdkCameraMediaMode * _Nonnull mode;
/// The camera orientation used when capturing AR content.
/// Determines whether the camera operates in portrait or landscape mode.
@property (nonatomic, readonly) enum TruvideoSdkCameraOrientation orientation;
/// Instantiates a new <code>TruvideoSdkARCameraConfiguration</code> using static method syntax.
/// This provides a convenient way to create configurations without directly initializing an instance.
/// \param flashMode The desired flash setting (default: <code>.off</code>).
///
/// \param orientation The camera’s orientation.
///
/// \param mode The media capture mode (default: <code>.videoAndPicture()</code>).
///
///
/// returns:
/// A new <code>TruvideoSdkARCameraConfiguration</code> instance.
+ (TruvideoSdkARCameraConfiguration * _Nonnull)instantiateWith:(enum TruvideoSdkCameraFlashMode)flashMode orientation:(enum TruvideoSdkCameraOrientation)orientation mode:(TruvideoSdkCameraMediaMode * _Nonnull)mode SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIApplication;
@class UIWindow;

/// Defines the application delegate for handling camera-related configurations.
/// <code>TruvideoSdkCameraAppDelegate</code> extends <code>UIApplicationDelegate</code> and provides control over <em>interface orientation lock</em> settings.
/// <h2>Overview</h2>
/// This protocol is responsible for:
/// <ul>
///   <li>
///     <em>Managing the orientation lock</em> for the camera.
///   </li>
///   <li>
///     <em>Defining supported interface orientations</em> for the application.
///   </li>
/// </ul>
/// <h2>Example Usage</h2>
/// \code
/// class AppDelegate: UIResponder, TruvideoSdkCameraAppDelegate {
///     var orientationLock: UIInterfaceOrientationMask = .portrait
///
///     func application(
///         _ application: UIApplication,
///         supportedInterfaceOrientationsFor window: UIWindow?
///     ) -> UIInterfaceOrientationMask {
///         return orientationLock
///     }
/// }
///
/// \endcode
SWIFT_PROTOCOL("_TtP17TruvideoSdkCamera28TruvideoSdkCameraAppDelegate_")
@protocol TruvideoSdkCameraAppDelegate <UIApplicationDelegate>
/// The current orientation lock for the application.
@property (nonatomic) UIInterfaceOrientationMask orientationLock;
/// Determines the supported interface orientations for the application.
/// This method allows the app to specify <em>which orientations</em> are permitted for a given window.
/// \param application The running application instance.
///
/// \param window The main application window.
///
///
/// returns:
/// A <code>UIInterfaceOrientationMask</code> specifying the supported orientations.
- (UIInterfaceOrientationMask)application:(UIApplication * _Nonnull)application supportedInterfaceOrientationsForWindow:(UIWindow * _Nullable)window SWIFT_WARN_UNUSED_RESULT;
@end

enum TruvideoSdkCameraImageFormat : NSInteger;
enum TruvideoSdkCameraLensFacing : NSInteger;
@class NSString;

/// A configuration object that defines camera behavior and capture settings.
/// This class encapsulates all the settings needed to configure the camera
/// for media capture, including lens selection, flash behavior, image format,
/// resolution options, and capture mode limits. It provides a centralized
/// way to manage camera configuration and ensures consistent behavior
/// across different capture sessions.
/// The configuration supports both front and back camera lenses, multiple
/// resolution options, various flash modes, and flexible media capture
/// modes. All settings have sensible defaults to simplify common use cases
/// while still allowing fine-grained customization when needed.
/// This class is designed to be Objective-C compatible and can be easily
/// integrated into existing iOS applications.
SWIFT_CLASS("_TtC17TruvideoSdkCamera30TruvideoSdkCameraConfiguration")
@interface TruvideoSdkCameraConfiguration : NSObject
/// The flash mode setting for the camera.
/// This property determines how the camera flash behaves during capture.
/// Options include off, on, auto, and other flash modes depending on
/// device capabilities and lighting conditions.
@property (nonatomic, readonly) enum TruvideoSdkCameraFlashMode flashMode;
/// The image format for captured photos.
/// This property specifies the file format used for saving captured
/// images. Common formats include JPEG, PNG, and HEIC. The format
/// affects file size, quality, and compatibility with different systems.
@property (nonatomic, readonly) enum TruvideoSdkCameraImageFormat imageFormat;
/// Indicates whether high-resolution photo capture is enabled.
/// When enabled, the camera will capture photos at the highest
/// available resolution for the selected camera lens. This may
/// impact performance and file size but provides maximum image quality.
@property (nonatomic, readonly) BOOL isHighResolutionPhotoEnabled;
/// The camera lens to use for capture.
/// This property specifies whether to use the front-facing or
/// back-facing camera lens. The choice affects the perspective
/// and capabilities available during capture.
@property (nonatomic, readonly) enum TruvideoSdkCameraLensFacing lensFacing;
/// The media capture mode and limits.
/// This property defines what types of media can be captured
/// (pictures, videos, or both) and sets limits on the number
/// of items and duration for each media type.
@property (nonatomic, readonly, strong) TruvideoSdkCameraMediaMode * _Nonnull mode;
/// The directory path where captured media will be saved.
/// This property specifies the file system location where
/// captured pictures and videos will be stored. The path
/// should be writable and accessible by the application.
@property (nonatomic, readonly, copy) NSString * _Nonnull outputPath;
/// Indicates whether media should be uploaded in a streaming fashion during capture.
/// This property determines whether captured media is uploaded to a remote
/// server as it is being recorded (streaming upload) or after capture is
/// complete (batch upload). When enabled, media data is transmitted
/// progressively during capture, which can reduce local storage requirements
/// but may impact network usage and upload reliability.
@property (nonatomic, readonly) BOOL streamingUpload;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface TruvideoSdkCameraConfiguration (SWIFT_EXTENSION(TruvideoSdkCamera))
/// Creates a new camera configuration with all parameters specified.
/// This factory method provides a comprehensive way to instantiate a camera
/// configuration with all available settings. It allows fine-grained control
/// over camera behavior including lens selection, resolution options, flash
/// settings, image format, capture mode, and output path.
/// The method accepts both resolution arrays (for available options) and
/// specific resolution selections (for current settings). This provides
/// flexibility in how the camera handles resolution selection and fallbacks.
/// warning:
/// This method is deprecated. Use the initializer <code>TruvideoSdkCameraConfiguration(...)</code> instead.
/// \param lensFacing The camera lens to use (front or back)
///
/// \param backResolution The specific resolution selected for the back camera (nil = auto-select)
///
/// \param backResolutions Available resolution options for the back camera
///
/// \param flashMode The flash mode setting for the camera
///
/// \param frontResolution The specific resolution selected for the front camera (nil = auto-select)
///
/// \param frontResolutions Available resolution options for the front camera
///
/// \param imageFormat The image format for captured photos (default: JPEG)
///
/// \param mode The media capture mode and limits
///
/// \param outputPath The directory path where captured media will be saved
///
///
/// returns:
/// A fully configured camera configuration instance
+ (TruvideoSdkCameraConfiguration * _Nonnull)instantiateWith:(enum TruvideoSdkCameraLensFacing)lensFacing imageFormat:(enum TruvideoSdkCameraImageFormat)imageFormat mode:(TruvideoSdkCameraMediaMode * _Nonnull)mode outputPath:(NSString * _Nonnull)outputPath SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use TruvideoSdkCameraConfiguration(...) initializer instead");
@end


/// An enumeration representing the camera flash mode settings.
/// This enum defines the available flash modes for camera capture, providing
/// control over whether the camera flash is active during photo or video
/// capture. It supports both Objective-C integration and JSON serialization
/// through Codable conformance, making it suitable for configuration storage
/// and cross-platform communication.
/// The enum uses string raw values for better readability and API consistency,
/// with uppercase values following common naming conventions. The flash mode
/// setting affects the lighting conditions during capture and can significantly
/// impact image quality in low-light environments.
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraFlashMode, open) {
/// Flash is disabled during capture.
/// This case represents the flash being turned off, which is useful
/// for natural lighting conditions or when additional lighting is
/// not desired. This mode is often preferred for outdoor photography
/// or when capturing subjects at a distance.
  TruvideoSdkCameraFlashModeOff = 0,
/// Flash is enabled during capture.
/// This case represents the flash being turned on, which provides
/// additional lighting during capture. This mode is useful for
/// low-light conditions, indoor photography, or when additional
/// illumination is needed to properly expose the subject.
  TruvideoSdkCameraFlashModeOn = 1,
};

/// An enumeration representing supported image formats for camera capture.
/// This enum defines the available image formats that can be used for
/// photo capture in the camera system. It provides a type-safe way to
/// specify image format preferences and ensures compatibility with
/// different use cases and quality requirements.
/// The enum uses string raw values for better readability and API
/// consistency, with uppercase values following common naming conventions.
/// Each format has distinct characteristics regarding compression,
/// quality, file size, and feature support.
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraImageFormat, open) {
/// JPEG image format.
/// Produces a <em>compressed image</em> with lossy compression,
/// resulting in smaller file sizes while maintaining reasonable quality.
  TruvideoSdkCameraImageFormatJpeg = 0,
/// PNG image format.
/// Produces a <em>lossless compressed image</em> with higher file size
/// but exact preservation of quality, including transparency.
  TruvideoSdkCameraImageFormatPng = 1,
};

/// An enumeration representing the camera lens orientation.
/// This enum defines the two possible camera lens orientations available
/// on iOS devices. It supports both Objective-C integration and JSON
/// serialization through Codable conformance, making it suitable for
/// cross-platform communication and persistent storage.
/// The enum uses string raw values for better readability and compatibility
/// with external systems, while maintaining type safety through the
/// RawRepresentable protocol. The string values are uppercase to follow
/// common API conventions.
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraLensFacing, open) {
/// The back-facing camera lens.
/// This case represents the primary camera lens located on the back
/// of the device. The back camera typically has higher resolution
/// and better image quality compared to the front camera, making
/// it ideal for most photography and video capture scenarios.
  TruvideoSdkCameraLensFacingBack = 0,
/// The front-facing camera lens.
/// This case represents the camera lens located on the front of the
/// device, typically used for selfies and video calls. The front
/// camera is designed for close-up shots and face detection features.
  TruvideoSdkCameraLensFacingFront = 1,
};

@class NSUUID;
enum TruvideoSdkCameraMediaType : NSInteger;

/// A model representing a captured media item from the camera.
/// This class encapsulates all the metadata and properties of a captured
/// media item, including pictures and videos. It provides comprehensive
/// information about the capture session, including timing, device
/// orientation, camera settings, and file location.
/// Each media item includes a unique identifier, creation timestamp,
/// file path for access, and detailed capture metadata such as
/// camera lens, orientation, resolution, and media type.
SWIFT_CLASS("_TtC17TruvideoSdkCamera22TruvideoSdkCameraMedia")
@interface TruvideoSdkCameraMedia : NSObject
/// A unique identifier for the media item.
@property (nonatomic, readonly, copy) NSUUID * _Nonnull id;
/// The timestamp when the media was captured.
@property (nonatomic, readonly) NSTimeInterval createdAt;
/// The duration of the media item in seconds.
@property (nonatomic, readonly) NSTimeInterval duration;
/// The file system path where the media is stored.
@property (nonatomic, readonly, copy) NSString * _Nonnull filePath;
/// The camera lens used to capture the media.
@property (nonatomic, readonly) enum TruvideoSdkCameraLensFacing lensFacing;
/// The device orientation when the media was captured.
@property (nonatomic, readonly) enum TruvideoSdkCameraOrientation orientation;
/// The type of media that was captured.
@property (nonatomic, readonly) enum TruvideoSdkCameraMediaType type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A configuration class that defines the media capture limits and constraints for the camera.
/// This class provides a unified way to configure how many pictures and videos can be captured,
/// along with duration limits for video recordings. It supports various capture modes including
/// single media capture, multiple media capture, and mixed media capture scenarios.
/// The class uses a flexible approach where maxMediaCount represents the total limit across
/// all media types, while individual limits (maxPictureCount, maxVideoCount) provide specific
/// constraints for each media type. When both total and specific limits are set, the more
/// restrictive limit takes precedence.
/// All factory methods provide sensible defaults and can be used to quickly create common
/// capture configurations without needing to understand the underlying limit calculations.
/// <h2>Examples</h2>
/// \code
/// // Single picture capture
/// let singlePictureMode = TruvideoSdkCameraMediaMode.singlePicture()
///
/// // Multiple pictures with limit
/// let pictureMode = TruvideoSdkCameraMediaMode.picture(pictureCount: 5)
///
/// // Single video with 30-second limit
/// let singleVideoMode = TruvideoSdkCameraMediaMode.singleVideo(videoDuration: 30)
///
/// // Multiple videos with limits
/// let videoMode = TruvideoSdkCameraMediaMode.video(videoCount: 3, videoDuration: 60)
///
/// // Mixed media with separate limits
/// let mixedMode = TruvideoSdkCameraMediaMode.videoAndPicture(
///     videoCount: 2,
///     pictureCount: 5,
///     videoDuration: 45
/// )
///
/// // Mixed media with total limit only
/// let totalLimitMode = TruvideoSdkCameraMediaMode.videoAndPicture(
///     mediaCount: 10,
///     videoDuration: 30
/// )
///
/// // Custom configuration
/// let customMode = TruvideoSdkCameraMediaMode(
///     maxMediaCount: 15,
///     maxPictureCount: 8,
///     maxVideoCount: 7,
///     maxVideoDuration: 60
/// )
///
/// \endcode
SWIFT_CLASS("_TtC17TruvideoSdkCamera26TruvideoSdkCameraMediaMode")
@interface TruvideoSdkCameraMediaMode : NSObject
/// Creates a mode configured for capturing a single picture.
/// This mode allows exactly one picture to be captured. Video capture is disabled.
/// This is useful for simple photo capture scenarios.
///
/// returns:
/// A media mode configured for single picture capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)singlePicture SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;

@interface TruvideoSdkCameraMediaMode (SWIFT_EXTENSION(TruvideoSdkCamera))
/// Creates a mode configured for capturing both videos and pictures with separate limits.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>videoAndPicture</code>
/// method but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>videoAndPicture(videoCount:pictureCount:videoDuration:)</code> instead.
/// \param videoCount Maximum number of videos (nil = unlimited)
///
/// \param pictureCount Maximum number of pictures (nil = unlimited)
///
/// \param videoDuration Maximum duration per video in seconds (nil = unlimited)
///
///
/// returns:
/// A media mode configured for mixed media capture with separate limits
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSVideoAndPictureWithVideoCount:(NSNumber * _Nullable)videoCount pictureCount:(NSNumber * _Nullable)pictureCount videoDuration:(NSNumber * _Nullable)videoDuration SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use videoAndPicture(videoCount:pictureCount:videoDuration:) instead");
/// Creates a mode configured for capturing a single video.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>singleVideo</code>
/// method but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>singleVideo(videoDuration:)</code> instead.
/// \param videoDuration Maximum video duration in seconds (nil = unlimited)
///
///
/// returns:
/// A media mode configured for single video capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSSingleVideoWithVideoDuration:(NSNumber * _Nullable)videoDuration SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use singleVideo(videoDuration:) instead");
/// Creates a mode configured for capturing a single picture.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>singlePicture</code>
/// method for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>singlePicture()</code> instead.
///
/// returns:
/// A media mode configured for single picture capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSSinglePicture SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use singlePicture() instead");
/// Creates a mode configured for capturing either a single video or picture.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>singleVideoOrPicture</code>
/// method but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>singleVideoOrPicture(videoDuration:)</code> instead.
/// \param videoDuration Maximum video duration in seconds (nil = unlimited)
///
///
/// returns:
/// A media mode configured for single video or picture capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSSingleVideoOrPictureWithVideoDuration:(NSNumber * _Nullable)videoDuration SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use singleVideoOrPicture(videoDuration:) instead");
/// Creates a mode configured for capturing multiple videos.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>video</code>
/// method but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>video(videoCount:videoDuration:)</code> instead.
/// \param videoCount Maximum number of videos (nil = unlimited)
///
/// \param videoDuration Maximum duration per video in seconds (nil = unlimited)
///
///
/// returns:
/// A media mode configured for multiple video capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSVideoWithVideoCount:(NSNumber * _Nullable)videoCount videoDuration:(NSNumber * _Nullable)videoDuration SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use video(videoCount:videoDuration:) instead");
/// Creates a mode configured for capturing multiple pictures.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>picture</code>
/// method but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>picture(pictureCount:)</code> instead.
/// \param pictureCount Maximum number of pictures (nil = unlimited)
///
///
/// returns:
/// A media mode configured for picture capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSPictureWithPictureCount:(NSNumber * _Nullable)pictureCount SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use picture(pictureCount:) instead");
/// Creates a mode configured for capturing both videos and pictures with a total limit.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>videoAndPicture</code>
/// method with total media count limit but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>videoAndPicture(mediaCount:videoDuration:)</code> instead.
/// \param mediaCount Maximum total media items (nil = unlimited)
///
/// \param videoDuration Maximum duration per video in seconds (nil = unlimited)
///
///
/// returns:
/// A media mode configured for mixed media capture with total limit
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSVideoAndPictureWithMediaCount:(NSNumber * _Nullable)mediaCount videoDuration:(NSNumber * _Nullable)videoDuration SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use videoAndPicture(mediaCount:videoDuration:) instead");
@end


/// An enumeration representing the different media types supported by the Truvideo SDK camera.
/// <code>TruvideoSdkCameraMediaType</code> conforms to <code>Codable</code> and <code>RawRepresentable</code>, allowing it to be
/// encoded and decoded from JSON. The raw values are stored as <code>String</code> representations.
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraMediaType, open) {
/// The media type representing a recorded video clip.
  TruvideoSdkCameraMediaTypeClip = 0,
/// The media type representing a captured photo.
  TruvideoSdkCameraMediaTypePhoto = 1,
};

/// An enumeration representing camera orientation states.
/// This enum defines the four possible camera orientations that correspond
/// to device orientation states. It provides a bridge between device
/// orientation detection and camera interface orientation requirements,
/// supporting both portrait and landscape orientations in all directions.
/// The enum uses string raw values for better readability and API consistency,
/// with underscore-separated uppercase values following common naming
/// conventions. It includes utility properties for converting between
/// different orientation representations and retrieving current device state.
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraOrientation, open) {
/// Upright portrait mode.
/// This case represents the standard portrait orientation where the device
/// is held vertically with the top of the device pointing upward. This is
/// the most common orientation for mobile photography and video capture.
  TruvideoSdkCameraOrientationPortrait = 0,
/// Landscape mode with the device rotated left.
/// This case represents landscape orientation where the device is rotated
/// 90 degrees counterclockwise from portrait. The left edge of the device
/// becomes the top edge in this orientation.
  TruvideoSdkCameraOrientationLandscapeLeft = 1,
/// Landscape mode with the device rotated right.
/// This case represents landscape orientation where the device is rotated
/// 90 degrees clockwise from portrait. The right edge of the device
/// becomes the top edge in this orientation.
  TruvideoSdkCameraOrientationLandscapeRight = 2,
};


/// Represents a camera resolution with width and height dimensions.
/// <code>TruvideoSdkCameraResolution</code> defines a camera resolution using integer width and height values.
/// This class provides a simple way to represent video capture resolutions and supports
/// JSON encoding for configuration storage and API communication.
/// <h2>Usage</h2>
/// \code
/// // Create a 1920x1080 resolution
/// let fullHD = TruvideoSdkCameraResolution(width: 1920, height: 1080)
///
/// // Create a 1280x720 resolution
/// let hd = TruvideoSdkCameraResolution(width: 1280, height: 720)
///
/// // Access resolution dimensions
/// print("Width: \(fullHD.width), Height: \(fullHD.height)")
///
/// \endcode<h2>Common Resolutions</h2>
/// Standard video resolutions include:
/// <ul>
///   <li>
///     <em>4K</em>: 3840×2160 (Ultra High Definition)
///   </li>
///   <li>
///     <em>1080p</em>: 1920×1080 (Full High Definition)
///   </li>
///   <li>
///     <em>720p</em>: 1280×720 (High Definition)
///   </li>
///   <li>
///     <em>480p</em>: 854×480 (Standard Definition)
///   </li>
///   <li>
///     <em>360p</em>: 640×360 (Low Definition)
///   </li>
/// </ul>
/// <h2>JSON Encoding</h2>
/// The class supports JSON encoding for API communication:
/// \code
/// let resolution = TruvideoSdkCameraResolution(width: 1920, height: 1080)
/// let encoder = JSONEncoder()
/// let data = try encoder.encode(resolution)
/// // Result: {"width": 1920, "height": 1080}
///
/// \endcode<h2>Objective-C Compatibility</h2>
/// The class is marked with <code>@objcMembers</code> for full Objective-C interoperability,
/// allowing seamless integration with existing Objective-C codebases.
/// <h2>Thread Safety</h2>
/// This class is thread-safe and can be used concurrently across multiple threads.
/// All properties are immutable once initialized.
/// note:
/// This class is deprecated. Use <code>AVCaptureSession.Preset</code> for resolution handling.
/// important:
/// Width and height values are stored as <code>Int32</code> for API compatibility.
SWIFT_CLASS("_TtC17TruvideoSdkCamera37TruvideoSdkCameraResolutionDeprecated")
@interface TruvideoSdkCameraResolutionDeprecated : NSObject
/// The height of the camera resolution in pixels.
/// This property represents the vertical dimension of the video capture resolution.
/// It’s stored as an <code>Int32</code> for API compatibility and JSON encoding support.
@property (nonatomic, readonly) int32_t height;
/// The width of the camera resolution in pixels.
/// This property represents the horizontal dimension of the video capture resolution.
/// It’s stored as an <code>Int32</code> for API compatibility and JSON encoding support.
@property (nonatomic, readonly) int32_t width;
/// Creates a new camera resolution with the specified width and height.
/// This initializer creates a resolution object with the given dimensions.
/// Both width and height must be positive values representing pixel dimensions.
/// \param width The horizontal dimension in pixels
///
/// \param height The vertical dimension in pixels
///
- (nonnull instancetype)initWithWidth:(int32_t)width height:(int32_t)height OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A result object containing the media items captured by the camera.
/// This class represents the outcome of a camera capture session, containing
/// all the media items (pictures and videos) that were successfully captured.
/// The result is designed to be easily serializable and can be encoded for
/// storage or transmission purposes.
/// The media array contains all captured items in the order they were captured,
/// allowing for chronological playback or processing. Each media item includes
/// its type, file path, metadata, and any associated properties.
SWIFT_CLASS("_TtC17TruvideoSdkCamera23TruvideoSdkCameraResult")
@interface TruvideoSdkCameraResult : NSObject
/// The collection of media items captured during the camera session.
/// This array contains all successfully captured pictures and videos,
/// ordered chronologically by capture time. Each media item includes
/// the file path, type information, and associated metadata.
@property (nonatomic, readonly, copy) NSArray<TruvideoSdkCameraMedia *> * _Nonnull media;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum TruvideoSdkCameraScannerCodeFormat : NSInteger;

/// Represents the result of a barcode or QR code scan.
/// The <code>TruvideoSdkCameraScannerCode</code> class contains <em>raw barcode data</em> and its associated <em>format type</em>.
/// <h2>Overview</h2>
/// When a barcode or QR code is scanned using the <em>Truvideo Scanner Camera</em>, this class stores:
/// <ul>
///   <li>
///     The <em>scanned code’s data</em> (<code>data</code>)
///   </li>
///   <li>
///     The <em>format of the scanned barcode</em> (<code>format</code>)
///   </li>
/// </ul>
/// <h2>Example Usage</h2>
/// \code
/// let scannedCode = TruvideoSdkCameraScannerCode(data: "123456789", format: .codeQR)
/// print("Scanned Data: \(scannedCode.data)")
/// print("Format: \(scannedCode.format)")
///
/// \endcode
SWIFT_CLASS("_TtC17TruvideoSdkCamera28TruvideoSdkCameraScannerCode")
@interface TruvideoSdkCameraScannerCode : NSObject
/// The raw data extracted from the scanned barcode.
@property (nonatomic, readonly, copy) NSString * _Nonnull data;
/// The type of barcode that was scanned.
@property (nonatomic, readonly) enum TruvideoSdkCameraScannerCodeFormat format;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Defines the supported barcode and QR code formats for the scanner.
/// <code>TruvideoSdkCameraScannerCodeFormat</code> provides the available barcode types that the <em>Truvideo Scanner Camera</em> can detect.
/// <h2>Supported Formats</h2>
/// <ul>
///   <li>
///     <code>code39</code>: <em>Code-39 barcode</em> (commonly used in logistics and inventory systems)
///   </li>
///   <li>
///     <code>code93</code>: <em>Code-93 barcode</em> (an extended version of Code-39 with higher data density)
///   </li>
///   <li>
///     <code>codeQR</code>: <em>QR Code</em> (widely used for mobile transactions, payments, and URLs)
///   </li>
///   <li>
///     <code>dataMatrix</code>: <em>DataMatrix Code</em> (used in packaging, manufacturing, and tracking applications)
///   </li>
/// </ul>
/// <h2>Example Usage</h2>
/// \code
/// let scannerConfig = TruvideoSdkScannerCameraConfiguration(
///     flashMode: .auto,
///     codeFormats: [.codeQR, .dataMatrix]
/// )
///
/// \endcode
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraScannerCodeFormat, open) {
/// Code-39 barcode format.
  TruvideoSdkCameraScannerCodeFormatCode39 = 0,
/// Code-93 barcode format.
  TruvideoSdkCameraScannerCodeFormatCode93 = 1,
/// QR Code format.
  TruvideoSdkCameraScannerCodeFormatCodeQR = 2,
/// DataMatrix barcode format.
  TruvideoSdkCameraScannerCodeFormatDataMatrix = 3,
};


/// Configuration settings for the <em>Truvideo Scanner Camera</em>.
/// This class allows developers to customize <em>flash mode, orientation, supported barcode types, and validation rules</em>.
/// <h2>Example Usage</h2>
/// \code
/// let scannerConfig = TruvideoSdkScannerCameraConfiguration(
///     flashMode: .auto,
///     orientation: .portrait,
///     codeFormats: [.codeQR, .dataMatrix],
///     autoClose: true
/// )
///
/// \endcode
SWIFT_CLASS("_TtC17TruvideoSdkCamera37TruvideoSdkScannerCameraConfiguration")
@interface TruvideoSdkScannerCameraConfiguration : NSObject
/// Specifies whether the <em>flash</em> is enabled during scanning.
@property (nonatomic, readonly) enum TruvideoSdkCameraFlashMode flashMode;
/// Defines the <em>camera orientation</em> during scanning.
@property (nonatomic, readonly) enum TruvideoSdkCameraOrientation orientation;
/// Determines whether the scanner <em>automatically closes</em> after a successful scan.
@property (nonatomic, readonly) BOOL autoClose;
/// Creates a scanner configuration with default settings.
/// \param flashMode The desired flash mode.
///
/// \param orientation The camera orientation.
///
/// \param autoClose Whether to automatically close after a scan.
///
///
/// returns:
/// A new scanner configuration instance.
+ (TruvideoSdkScannerCameraConfiguration * _Nonnull)instantiateWith:(enum TruvideoSdkCameraFlashMode)flashMode orientation:(enum TruvideoSdkCameraOrientation)orientation autoClose:(BOOL)autoClose SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end














@interface UIViewController (SWIFT_EXTENSION(TruvideoSdkCamera))
/// Presents a full-screen camera interface for media capture.
/// This function creates and presents a camera view that allows users to capture
/// pictures and videos according to the specified configuration. The camera
/// interface is displayed as a full-screen modal that covers the entire screen
/// and provides a native camera experience with capture controls.
/// The function uses UIKit’s presentation system to show a SwiftUI camera view
/// wrapped in a UIHostingController. The camera view is presented modally with
/// full-screen presentation style, ensuring it takes over the entire display
/// area for an immersive camera experience.
/// The camera configuration can be customized to control capture limits,
/// video duration, media types, and other camera behavior settings. When the
/// user completes their capture session, the onComplete closure is called
/// with the captured media results.
/// \param preset Configuration settings for the camera behavior (default: default configuration)
///
/// \param onComplete Closure called when the camera session completes with captured media
///
- (void)presentTruvideoSdkCameraViewWithPreset:(TruvideoSdkCameraConfiguration * _Nonnull)preset onComplete:(void (^ _Nonnull)(TruvideoSdkCameraResult * _Nonnull))onComplete;
@end


@interface UIViewController (SWIFT_EXTENSION(TruvideoSdkCamera))
/// Presents the AR camera view over the full screen.
/// The camera view is presented <em>modally in full screen</em>, and once the session ends, the result is passed back to the caller.
/// \param preset A <code>TruvideoSdkARCameraConfiguration</code> object containing the AR camera configuration.
///
/// \param onComplete A callback function that receives a <code>TruvideoSdkCameraResult</code> containing captured media.
///
- (void)presentTruvideoSdkARCameraViewWithPreset:(TruvideoSdkARCameraConfiguration * _Nonnull)preset onComplete:(void (^ _Nonnull)(TruvideoSdkCameraResult * _Nonnull))onComplete;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef TRUVIDEOSDKCAMERA_SWIFT_H
#define TRUVIDEOSDKCAMERA_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TruvideoSdkCamera",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)




























/// A registry for the TruVideo SDK Camera library that provides library metadata and configuration.
SWIFT_CLASS("_TtC17TruvideoSdkCamera16SDKCameraLibrary")
@interface SDKCameraLibrary : NSObject
/// Registers the camera library with the SDK’s library registry.
/// This static method registers the camera library instance with the global
/// library registry system. It should be called during SDK initialization
/// to ensure the camera library is properly registered and available for
/// dependency injection and service discovery.
+ (void)register;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum TruvideoSdkCameraFlashMode : NSInteger;
@class TruvideoSdkCameraMediaMode;
enum TruvideoSdkCameraOrientation : NSInteger;

/// A configuration object for setting up the AR Camera in <code>TruvideoSdkCamera</code>.
/// <code>TruvideoSdkARCameraConfiguration</code> allows you to customize the AR Camera’s behavior, including flash settings, capture mode,
/// and camera orientation.
/// <h2>Example Usage</h2>
/// \code
/// let arConfig = TruvideoSdkARCameraConfiguration(
///     flashMode: .auto,
///     mode: .videoAndPicture(videoMaxCount: 3, pictureMaxCount: 5, durationLimit: 15),
///     orientation: .portrait
/// )
///
/// \endcodeThis configuration can be passed to <code>presentTruvideoSdkARCameraView</code> to launch the AR Camera with the specified settings.
/// <h2>See Also</h2>
/// <ul>
///   <li>
///     <code>TruvideoSdkCameraFlashMode</code>
///   </li>
///   <li>
///     <code>TruvideoSdkCameraMediaMode</code>
///   </li>
///   <li>
///     <code>TruvideoSdkCameraOrientation</code>
///   </li>
/// </ul>
SWIFT_CLASS("_TtC17TruvideoSdkCamera32TruvideoSdkARCameraConfiguration")
@interface TruvideoSdkARCameraConfiguration : NSObject
/// The flash mode setting for the AR Camera.
/// Determines whether the flash is on, off, or set to auto mode.
@property (nonatomic, readonly) enum TruvideoSdkCameraFlashMode flashMode;
/// The media capture mode for the AR Camera.
/// Defines whether the camera captures photos, videos, or both.
@property (nonatomic, readonly, strong) TruvideoSdkCameraMediaMode * _Nonnull mode;
/// The camera orientation used when capturing AR content.
/// Determines whether the camera operates in portrait or landscape mode.
@property (nonatomic, readonly) enum TruvideoSdkCameraOrientation orientation;
/// Instantiates a new <code>TruvideoSdkARCameraConfiguration</code> using static method syntax.
/// This provides a convenient way to create configurations without directly initializing an instance.
/// \param flashMode The desired flash setting (default: <code>.off</code>).
///
/// \param orientation The camera’s orientation.
///
/// \param mode The media capture mode (default: <code>.videoAndPicture()</code>).
///
///
/// returns:
/// A new <code>TruvideoSdkARCameraConfiguration</code> instance.
+ (TruvideoSdkARCameraConfiguration * _Nonnull)instantiateWith:(enum TruvideoSdkCameraFlashMode)flashMode orientation:(enum TruvideoSdkCameraOrientation)orientation mode:(TruvideoSdkCameraMediaMode * _Nonnull)mode SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIApplication;
@class UIWindow;

/// Defines the application delegate for handling camera-related configurations.
/// <code>TruvideoSdkCameraAppDelegate</code> extends <code>UIApplicationDelegate</code> and provides control over <em>interface orientation lock</em> settings.
/// <h2>Overview</h2>
/// This protocol is responsible for:
/// <ul>
///   <li>
///     <em>Managing the orientation lock</em> for the camera.
///   </li>
///   <li>
///     <em>Defining supported interface orientations</em> for the application.
///   </li>
/// </ul>
/// <h2>Example Usage</h2>
/// \code
/// class AppDelegate: UIResponder, TruvideoSdkCameraAppDelegate {
///     var orientationLock: UIInterfaceOrientationMask = .portrait
///
///     func application(
///         _ application: UIApplication,
///         supportedInterfaceOrientationsFor window: UIWindow?
///     ) -> UIInterfaceOrientationMask {
///         return orientationLock
///     }
/// }
///
/// \endcode
SWIFT_PROTOCOL("_TtP17TruvideoSdkCamera28TruvideoSdkCameraAppDelegate_")
@protocol TruvideoSdkCameraAppDelegate <UIApplicationDelegate>
/// The current orientation lock for the application.
@property (nonatomic) UIInterfaceOrientationMask orientationLock;
/// Determines the supported interface orientations for the application.
/// This method allows the app to specify <em>which orientations</em> are permitted for a given window.
/// \param application The running application instance.
///
/// \param window The main application window.
///
///
/// returns:
/// A <code>UIInterfaceOrientationMask</code> specifying the supported orientations.
- (UIInterfaceOrientationMask)application:(UIApplication * _Nonnull)application supportedInterfaceOrientationsForWindow:(UIWindow * _Nullable)window SWIFT_WARN_UNUSED_RESULT;
@end

enum TruvideoSdkCameraImageFormat : NSInteger;
enum TruvideoSdkCameraLensFacing : NSInteger;
@class NSString;

/// A configuration object that defines camera behavior and capture settings.
/// This class encapsulates all the settings needed to configure the camera
/// for media capture, including lens selection, flash behavior, image format,
/// resolution options, and capture mode limits. It provides a centralized
/// way to manage camera configuration and ensures consistent behavior
/// across different capture sessions.
/// The configuration supports both front and back camera lenses, multiple
/// resolution options, various flash modes, and flexible media capture
/// modes. All settings have sensible defaults to simplify common use cases
/// while still allowing fine-grained customization when needed.
/// This class is designed to be Objective-C compatible and can be easily
/// integrated into existing iOS applications.
SWIFT_CLASS("_TtC17TruvideoSdkCamera30TruvideoSdkCameraConfiguration")
@interface TruvideoSdkCameraConfiguration : NSObject
/// The flash mode setting for the camera.
/// This property determines how the camera flash behaves during capture.
/// Options include off, on, auto, and other flash modes depending on
/// device capabilities and lighting conditions.
@property (nonatomic, readonly) enum TruvideoSdkCameraFlashMode flashMode;
/// The image format for captured photos.
/// This property specifies the file format used for saving captured
/// images. Common formats include JPEG, PNG, and HEIC. The format
/// affects file size, quality, and compatibility with different systems.
@property (nonatomic, readonly) enum TruvideoSdkCameraImageFormat imageFormat;
/// Indicates whether high-resolution photo capture is enabled.
/// When enabled, the camera will capture photos at the highest
/// available resolution for the selected camera lens. This may
/// impact performance and file size but provides maximum image quality.
@property (nonatomic, readonly) BOOL isHighResolutionPhotoEnabled;
/// The camera lens to use for capture.
/// This property specifies whether to use the front-facing or
/// back-facing camera lens. The choice affects the perspective
/// and capabilities available during capture.
@property (nonatomic, readonly) enum TruvideoSdkCameraLensFacing lensFacing;
/// The media capture mode and limits.
/// This property defines what types of media can be captured
/// (pictures, videos, or both) and sets limits on the number
/// of items and duration for each media type.
@property (nonatomic, readonly, strong) TruvideoSdkCameraMediaMode * _Nonnull mode;
/// The directory path where captured media will be saved.
/// This property specifies the file system location where
/// captured pictures and videos will be stored. The path
/// should be writable and accessible by the application.
@property (nonatomic, readonly, copy) NSString * _Nonnull outputPath;
/// Indicates whether media should be uploaded in a streaming fashion during capture.
/// This property determines whether captured media is uploaded to a remote
/// server as it is being recorded (streaming upload) or after capture is
/// complete (batch upload). When enabled, media data is transmitted
/// progressively during capture, which can reduce local storage requirements
/// but may impact network usage and upload reliability.
@property (nonatomic, readonly) BOOL streamingUpload;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface TruvideoSdkCameraConfiguration (SWIFT_EXTENSION(TruvideoSdkCamera))
/// Creates a new camera configuration with all parameters specified.
/// This factory method provides a comprehensive way to instantiate a camera
/// configuration with all available settings. It allows fine-grained control
/// over camera behavior including lens selection, resolution options, flash
/// settings, image format, capture mode, and output path.
/// The method accepts both resolution arrays (for available options) and
/// specific resolution selections (for current settings). This provides
/// flexibility in how the camera handles resolution selection and fallbacks.
/// warning:
/// This method is deprecated. Use the initializer <code>TruvideoSdkCameraConfiguration(...)</code> instead.
/// \param lensFacing The camera lens to use (front or back)
///
/// \param backResolution The specific resolution selected for the back camera (nil = auto-select)
///
/// \param backResolutions Available resolution options for the back camera
///
/// \param flashMode The flash mode setting for the camera
///
/// \param frontResolution The specific resolution selected for the front camera (nil = auto-select)
///
/// \param frontResolutions Available resolution options for the front camera
///
/// \param imageFormat The image format for captured photos (default: JPEG)
///
/// \param mode The media capture mode and limits
///
/// \param outputPath The directory path where captured media will be saved
///
///
/// returns:
/// A fully configured camera configuration instance
+ (TruvideoSdkCameraConfiguration * _Nonnull)instantiateWith:(enum TruvideoSdkCameraLensFacing)lensFacing imageFormat:(enum TruvideoSdkCameraImageFormat)imageFormat mode:(TruvideoSdkCameraMediaMode * _Nonnull)mode outputPath:(NSString * _Nonnull)outputPath SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use TruvideoSdkCameraConfiguration(...) initializer instead");
@end


/// An enumeration representing the camera flash mode settings.
/// This enum defines the available flash modes for camera capture, providing
/// control over whether the camera flash is active during photo or video
/// capture. It supports both Objective-C integration and JSON serialization
/// through Codable conformance, making it suitable for configuration storage
/// and cross-platform communication.
/// The enum uses string raw values for better readability and API consistency,
/// with uppercase values following common naming conventions. The flash mode
/// setting affects the lighting conditions during capture and can significantly
/// impact image quality in low-light environments.
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraFlashMode, open) {
/// Flash is disabled during capture.
/// This case represents the flash being turned off, which is useful
/// for natural lighting conditions or when additional lighting is
/// not desired. This mode is often preferred for outdoor photography
/// or when capturing subjects at a distance.
  TruvideoSdkCameraFlashModeOff = 0,
/// Flash is enabled during capture.
/// This case represents the flash being turned on, which provides
/// additional lighting during capture. This mode is useful for
/// low-light conditions, indoor photography, or when additional
/// illumination is needed to properly expose the subject.
  TruvideoSdkCameraFlashModeOn = 1,
};

/// An enumeration representing supported image formats for camera capture.
/// This enum defines the available image formats that can be used for
/// photo capture in the camera system. It provides a type-safe way to
/// specify image format preferences and ensures compatibility with
/// different use cases and quality requirements.
/// The enum uses string raw values for better readability and API
/// consistency, with uppercase values following common naming conventions.
/// Each format has distinct characteristics regarding compression,
/// quality, file size, and feature support.
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraImageFormat, open) {
/// JPEG image format.
/// Produces a <em>compressed image</em> with lossy compression,
/// resulting in smaller file sizes while maintaining reasonable quality.
  TruvideoSdkCameraImageFormatJpeg = 0,
/// PNG image format.
/// Produces a <em>lossless compressed image</em> with higher file size
/// but exact preservation of quality, including transparency.
  TruvideoSdkCameraImageFormatPng = 1,
};

/// An enumeration representing the camera lens orientation.
/// This enum defines the two possible camera lens orientations available
/// on iOS devices. It supports both Objective-C integration and JSON
/// serialization through Codable conformance, making it suitable for
/// cross-platform communication and persistent storage.
/// The enum uses string raw values for better readability and compatibility
/// with external systems, while maintaining type safety through the
/// RawRepresentable protocol. The string values are uppercase to follow
/// common API conventions.
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraLensFacing, open) {
/// The back-facing camera lens.
/// This case represents the primary camera lens located on the back
/// of the device. The back camera typically has higher resolution
/// and better image quality compared to the front camera, making
/// it ideal for most photography and video capture scenarios.
  TruvideoSdkCameraLensFacingBack = 0,
/// The front-facing camera lens.
/// This case represents the camera lens located on the front of the
/// device, typically used for selfies and video calls. The front
/// camera is designed for close-up shots and face detection features.
  TruvideoSdkCameraLensFacingFront = 1,
};

@class NSUUID;
enum TruvideoSdkCameraMediaType : NSInteger;

/// A model representing a captured media item from the camera.
/// This class encapsulates all the metadata and properties of a captured
/// media item, including pictures and videos. It provides comprehensive
/// information about the capture session, including timing, device
/// orientation, camera settings, and file location.
/// Each media item includes a unique identifier, creation timestamp,
/// file path for access, and detailed capture metadata such as
/// camera lens, orientation, resolution, and media type.
SWIFT_CLASS("_TtC17TruvideoSdkCamera22TruvideoSdkCameraMedia")
@interface TruvideoSdkCameraMedia : NSObject
/// A unique identifier for the media item.
@property (nonatomic, readonly, copy) NSUUID * _Nonnull id;
/// The timestamp when the media was captured.
@property (nonatomic, readonly) NSTimeInterval createdAt;
/// The duration of the media item in seconds.
@property (nonatomic, readonly) NSTimeInterval duration;
/// The file system path where the media is stored.
@property (nonatomic, readonly, copy) NSString * _Nonnull filePath;
/// The camera lens used to capture the media.
@property (nonatomic, readonly) enum TruvideoSdkCameraLensFacing lensFacing;
/// The device orientation when the media was captured.
@property (nonatomic, readonly) enum TruvideoSdkCameraOrientation orientation;
/// The type of media that was captured.
@property (nonatomic, readonly) enum TruvideoSdkCameraMediaType type;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A configuration class that defines the media capture limits and constraints for the camera.
/// This class provides a unified way to configure how many pictures and videos can be captured,
/// along with duration limits for video recordings. It supports various capture modes including
/// single media capture, multiple media capture, and mixed media capture scenarios.
/// The class uses a flexible approach where maxMediaCount represents the total limit across
/// all media types, while individual limits (maxPictureCount, maxVideoCount) provide specific
/// constraints for each media type. When both total and specific limits are set, the more
/// restrictive limit takes precedence.
/// All factory methods provide sensible defaults and can be used to quickly create common
/// capture configurations without needing to understand the underlying limit calculations.
/// <h2>Examples</h2>
/// \code
/// // Single picture capture
/// let singlePictureMode = TruvideoSdkCameraMediaMode.singlePicture()
///
/// // Multiple pictures with limit
/// let pictureMode = TruvideoSdkCameraMediaMode.picture(pictureCount: 5)
///
/// // Single video with 30-second limit
/// let singleVideoMode = TruvideoSdkCameraMediaMode.singleVideo(videoDuration: 30)
///
/// // Multiple videos with limits
/// let videoMode = TruvideoSdkCameraMediaMode.video(videoCount: 3, videoDuration: 60)
///
/// // Mixed media with separate limits
/// let mixedMode = TruvideoSdkCameraMediaMode.videoAndPicture(
///     videoCount: 2,
///     pictureCount: 5,
///     videoDuration: 45
/// )
///
/// // Mixed media with total limit only
/// let totalLimitMode = TruvideoSdkCameraMediaMode.videoAndPicture(
///     mediaCount: 10,
///     videoDuration: 30
/// )
///
/// // Custom configuration
/// let customMode = TruvideoSdkCameraMediaMode(
///     maxMediaCount: 15,
///     maxPictureCount: 8,
///     maxVideoCount: 7,
///     maxVideoDuration: 60
/// )
///
/// \endcode
SWIFT_CLASS("_TtC17TruvideoSdkCamera26TruvideoSdkCameraMediaMode")
@interface TruvideoSdkCameraMediaMode : NSObject
/// Creates a mode configured for capturing a single picture.
/// This mode allows exactly one picture to be captured. Video capture is disabled.
/// This is useful for simple photo capture scenarios.
///
/// returns:
/// A media mode configured for single picture capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)singlePicture SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSNumber;

@interface TruvideoSdkCameraMediaMode (SWIFT_EXTENSION(TruvideoSdkCamera))
/// Creates a mode configured for capturing both videos and pictures with separate limits.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>videoAndPicture</code>
/// method but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>videoAndPicture(videoCount:pictureCount:videoDuration:)</code> instead.
/// \param videoCount Maximum number of videos (nil = unlimited)
///
/// \param pictureCount Maximum number of pictures (nil = unlimited)
///
/// \param videoDuration Maximum duration per video in seconds (nil = unlimited)
///
///
/// returns:
/// A media mode configured for mixed media capture with separate limits
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSVideoAndPictureWithVideoCount:(NSNumber * _Nullable)videoCount pictureCount:(NSNumber * _Nullable)pictureCount videoDuration:(NSNumber * _Nullable)videoDuration SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use videoAndPicture(videoCount:pictureCount:videoDuration:) instead");
/// Creates a mode configured for capturing a single video.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>singleVideo</code>
/// method but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>singleVideo(videoDuration:)</code> instead.
/// \param videoDuration Maximum video duration in seconds (nil = unlimited)
///
///
/// returns:
/// A media mode configured for single video capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSSingleVideoWithVideoDuration:(NSNumber * _Nullable)videoDuration SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use singleVideo(videoDuration:) instead");
/// Creates a mode configured for capturing a single picture.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>singlePicture</code>
/// method for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>singlePicture()</code> instead.
///
/// returns:
/// A media mode configured for single picture capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSSinglePicture SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use singlePicture() instead");
/// Creates a mode configured for capturing either a single video or picture.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>singleVideoOrPicture</code>
/// method but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>singleVideoOrPicture(videoDuration:)</code> instead.
/// \param videoDuration Maximum video duration in seconds (nil = unlimited)
///
///
/// returns:
/// A media mode configured for single video or picture capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSSingleVideoOrPictureWithVideoDuration:(NSNumber * _Nullable)videoDuration SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use singleVideoOrPicture(videoDuration:) instead");
/// Creates a mode configured for capturing multiple videos.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>video</code>
/// method but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>video(videoCount:videoDuration:)</code> instead.
/// \param videoCount Maximum number of videos (nil = unlimited)
///
/// \param videoDuration Maximum duration per video in seconds (nil = unlimited)
///
///
/// returns:
/// A media mode configured for multiple video capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSVideoWithVideoCount:(NSNumber * _Nullable)videoCount videoDuration:(NSNumber * _Nullable)videoDuration SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use video(videoCount:videoDuration:) instead");
/// Creates a mode configured for capturing multiple pictures.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>picture</code>
/// method but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>picture(pictureCount:)</code> instead.
/// \param pictureCount Maximum number of pictures (nil = unlimited)
///
///
/// returns:
/// A media mode configured for picture capture
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSPictureWithPictureCount:(NSNumber * _Nullable)pictureCount SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use picture(pictureCount:) instead");
/// Creates a mode configured for capturing both videos and pictures with a total limit.
/// This Objective-C wrapper method provides the same functionality as the Swift <code>videoAndPicture</code>
/// method with total media count limit but accepts NSNumber parameters for better Objective-C compatibility.
/// warning:
/// This method is deprecated. Use <code>videoAndPicture(mediaCount:videoDuration:)</code> instead.
/// \param mediaCount Maximum total media items (nil = unlimited)
///
/// \param videoDuration Maximum duration per video in seconds (nil = unlimited)
///
///
/// returns:
/// A media mode configured for mixed media capture with total limit
+ (TruvideoSdkCameraMediaMode * _Nonnull)NSVideoAndPictureWithMediaCount:(NSNumber * _Nullable)mediaCount videoDuration:(NSNumber * _Nullable)videoDuration SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Use videoAndPicture(mediaCount:videoDuration:) instead");
@end


/// An enumeration representing the different media types supported by the Truvideo SDK camera.
/// <code>TruvideoSdkCameraMediaType</code> conforms to <code>Codable</code> and <code>RawRepresentable</code>, allowing it to be
/// encoded and decoded from JSON. The raw values are stored as <code>String</code> representations.
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraMediaType, open) {
/// The media type representing a recorded video clip.
  TruvideoSdkCameraMediaTypeClip = 0,
/// The media type representing a captured photo.
  TruvideoSdkCameraMediaTypePhoto = 1,
};

/// An enumeration representing camera orientation states.
/// This enum defines the four possible camera orientations that correspond
/// to device orientation states. It provides a bridge between device
/// orientation detection and camera interface orientation requirements,
/// supporting both portrait and landscape orientations in all directions.
/// The enum uses string raw values for better readability and API consistency,
/// with underscore-separated uppercase values following common naming
/// conventions. It includes utility properties for converting between
/// different orientation representations and retrieving current device state.
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraOrientation, open) {
/// Upright portrait mode.
/// This case represents the standard portrait orientation where the device
/// is held vertically with the top of the device pointing upward. This is
/// the most common orientation for mobile photography and video capture.
  TruvideoSdkCameraOrientationPortrait = 0,
/// Landscape mode with the device rotated left.
/// This case represents landscape orientation where the device is rotated
/// 90 degrees counterclockwise from portrait. The left edge of the device
/// becomes the top edge in this orientation.
  TruvideoSdkCameraOrientationLandscapeLeft = 1,
/// Landscape mode with the device rotated right.
/// This case represents landscape orientation where the device is rotated
/// 90 degrees clockwise from portrait. The right edge of the device
/// becomes the top edge in this orientation.
  TruvideoSdkCameraOrientationLandscapeRight = 2,
};


/// Represents a camera resolution with width and height dimensions.
/// <code>TruvideoSdkCameraResolution</code> defines a camera resolution using integer width and height values.
/// This class provides a simple way to represent video capture resolutions and supports
/// JSON encoding for configuration storage and API communication.
/// <h2>Usage</h2>
/// \code
/// // Create a 1920x1080 resolution
/// let fullHD = TruvideoSdkCameraResolution(width: 1920, height: 1080)
///
/// // Create a 1280x720 resolution
/// let hd = TruvideoSdkCameraResolution(width: 1280, height: 720)
///
/// // Access resolution dimensions
/// print("Width: \(fullHD.width), Height: \(fullHD.height)")
///
/// \endcode<h2>Common Resolutions</h2>
/// Standard video resolutions include:
/// <ul>
///   <li>
///     <em>4K</em>: 3840×2160 (Ultra High Definition)
///   </li>
///   <li>
///     <em>1080p</em>: 1920×1080 (Full High Definition)
///   </li>
///   <li>
///     <em>720p</em>: 1280×720 (High Definition)
///   </li>
///   <li>
///     <em>480p</em>: 854×480 (Standard Definition)
///   </li>
///   <li>
///     <em>360p</em>: 640×360 (Low Definition)
///   </li>
/// </ul>
/// <h2>JSON Encoding</h2>
/// The class supports JSON encoding for API communication:
/// \code
/// let resolution = TruvideoSdkCameraResolution(width: 1920, height: 1080)
/// let encoder = JSONEncoder()
/// let data = try encoder.encode(resolution)
/// // Result: {"width": 1920, "height": 1080}
///
/// \endcode<h2>Objective-C Compatibility</h2>
/// The class is marked with <code>@objcMembers</code> for full Objective-C interoperability,
/// allowing seamless integration with existing Objective-C codebases.
/// <h2>Thread Safety</h2>
/// This class is thread-safe and can be used concurrently across multiple threads.
/// All properties are immutable once initialized.
/// note:
/// This class is deprecated. Use <code>AVCaptureSession.Preset</code> for resolution handling.
/// important:
/// Width and height values are stored as <code>Int32</code> for API compatibility.
SWIFT_CLASS("_TtC17TruvideoSdkCamera37TruvideoSdkCameraResolutionDeprecated")
@interface TruvideoSdkCameraResolutionDeprecated : NSObject
/// The height of the camera resolution in pixels.
/// This property represents the vertical dimension of the video capture resolution.
/// It’s stored as an <code>Int32</code> for API compatibility and JSON encoding support.
@property (nonatomic, readonly) int32_t height;
/// The width of the camera resolution in pixels.
/// This property represents the horizontal dimension of the video capture resolution.
/// It’s stored as an <code>Int32</code> for API compatibility and JSON encoding support.
@property (nonatomic, readonly) int32_t width;
/// Creates a new camera resolution with the specified width and height.
/// This initializer creates a resolution object with the given dimensions.
/// Both width and height must be positive values representing pixel dimensions.
/// \param width The horizontal dimension in pixels
///
/// \param height The vertical dimension in pixels
///
- (nonnull instancetype)initWithWidth:(int32_t)width height:(int32_t)height OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A result object containing the media items captured by the camera.
/// This class represents the outcome of a camera capture session, containing
/// all the media items (pictures and videos) that were successfully captured.
/// The result is designed to be easily serializable and can be encoded for
/// storage or transmission purposes.
/// The media array contains all captured items in the order they were captured,
/// allowing for chronological playback or processing. Each media item includes
/// its type, file path, metadata, and any associated properties.
SWIFT_CLASS("_TtC17TruvideoSdkCamera23TruvideoSdkCameraResult")
@interface TruvideoSdkCameraResult : NSObject
/// The collection of media items captured during the camera session.
/// This array contains all successfully captured pictures and videos,
/// ordered chronologically by capture time. Each media item includes
/// the file path, type information, and associated metadata.
@property (nonatomic, readonly, copy) NSArray<TruvideoSdkCameraMedia *> * _Nonnull media;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum TruvideoSdkCameraScannerCodeFormat : NSInteger;

/// Represents the result of a barcode or QR code scan.
/// The <code>TruvideoSdkCameraScannerCode</code> class contains <em>raw barcode data</em> and its associated <em>format type</em>.
/// <h2>Overview</h2>
/// When a barcode or QR code is scanned using the <em>Truvideo Scanner Camera</em>, this class stores:
/// <ul>
///   <li>
///     The <em>scanned code’s data</em> (<code>data</code>)
///   </li>
///   <li>
///     The <em>format of the scanned barcode</em> (<code>format</code>)
///   </li>
/// </ul>
/// <h2>Example Usage</h2>
/// \code
/// let scannedCode = TruvideoSdkCameraScannerCode(data: "123456789", format: .codeQR)
/// print("Scanned Data: \(scannedCode.data)")
/// print("Format: \(scannedCode.format)")
///
/// \endcode
SWIFT_CLASS("_TtC17TruvideoSdkCamera28TruvideoSdkCameraScannerCode")
@interface TruvideoSdkCameraScannerCode : NSObject
/// The raw data extracted from the scanned barcode.
@property (nonatomic, readonly, copy) NSString * _Nonnull data;
/// The type of barcode that was scanned.
@property (nonatomic, readonly) enum TruvideoSdkCameraScannerCodeFormat format;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Defines the supported barcode and QR code formats for the scanner.
/// <code>TruvideoSdkCameraScannerCodeFormat</code> provides the available barcode types that the <em>Truvideo Scanner Camera</em> can detect.
/// <h2>Supported Formats</h2>
/// <ul>
///   <li>
///     <code>code39</code>: <em>Code-39 barcode</em> (commonly used in logistics and inventory systems)
///   </li>
///   <li>
///     <code>code93</code>: <em>Code-93 barcode</em> (an extended version of Code-39 with higher data density)
///   </li>
///   <li>
///     <code>codeQR</code>: <em>QR Code</em> (widely used for mobile transactions, payments, and URLs)
///   </li>
///   <li>
///     <code>dataMatrix</code>: <em>DataMatrix Code</em> (used in packaging, manufacturing, and tracking applications)
///   </li>
/// </ul>
/// <h2>Example Usage</h2>
/// \code
/// let scannerConfig = TruvideoSdkScannerCameraConfiguration(
///     flashMode: .auto,
///     codeFormats: [.codeQR, .dataMatrix]
/// )
///
/// \endcode
typedef SWIFT_ENUM(NSInteger, TruvideoSdkCameraScannerCodeFormat, open) {
/// Code-39 barcode format.
  TruvideoSdkCameraScannerCodeFormatCode39 = 0,
/// Code-93 barcode format.
  TruvideoSdkCameraScannerCodeFormatCode93 = 1,
/// QR Code format.
  TruvideoSdkCameraScannerCodeFormatCodeQR = 2,
/// DataMatrix barcode format.
  TruvideoSdkCameraScannerCodeFormatDataMatrix = 3,
};


/// Configuration settings for the <em>Truvideo Scanner Camera</em>.
/// This class allows developers to customize <em>flash mode, orientation, supported barcode types, and validation rules</em>.
/// <h2>Example Usage</h2>
/// \code
/// let scannerConfig = TruvideoSdkScannerCameraConfiguration(
///     flashMode: .auto,
///     orientation: .portrait,
///     codeFormats: [.codeQR, .dataMatrix],
///     autoClose: true
/// )
///
/// \endcode
SWIFT_CLASS("_TtC17TruvideoSdkCamera37TruvideoSdkScannerCameraConfiguration")
@interface TruvideoSdkScannerCameraConfiguration : NSObject
/// Specifies whether the <em>flash</em> is enabled during scanning.
@property (nonatomic, readonly) enum TruvideoSdkCameraFlashMode flashMode;
/// Defines the <em>camera orientation</em> during scanning.
@property (nonatomic, readonly) enum TruvideoSdkCameraOrientation orientation;
/// Determines whether the scanner <em>automatically closes</em> after a successful scan.
@property (nonatomic, readonly) BOOL autoClose;
/// Creates a scanner configuration with default settings.
/// \param flashMode The desired flash mode.
///
/// \param orientation The camera orientation.
///
/// \param autoClose Whether to automatically close after a scan.
///
///
/// returns:
/// A new scanner configuration instance.
+ (TruvideoSdkScannerCameraConfiguration * _Nonnull)instantiateWith:(enum TruvideoSdkCameraFlashMode)flashMode orientation:(enum TruvideoSdkCameraOrientation)orientation autoClose:(BOOL)autoClose SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end














@interface UIViewController (SWIFT_EXTENSION(TruvideoSdkCamera))
/// Presents a full-screen camera interface for media capture.
/// This function creates and presents a camera view that allows users to capture
/// pictures and videos according to the specified configuration. The camera
/// interface is displayed as a full-screen modal that covers the entire screen
/// and provides a native camera experience with capture controls.
/// The function uses UIKit’s presentation system to show a SwiftUI camera view
/// wrapped in a UIHostingController. The camera view is presented modally with
/// full-screen presentation style, ensuring it takes over the entire display
/// area for an immersive camera experience.
/// The camera configuration can be customized to control capture limits,
/// video duration, media types, and other camera behavior settings. When the
/// user completes their capture session, the onComplete closure is called
/// with the captured media results.
/// \param preset Configuration settings for the camera behavior (default: default configuration)
///
/// \param onComplete Closure called when the camera session completes with captured media
///
- (void)presentTruvideoSdkCameraViewWithPreset:(TruvideoSdkCameraConfiguration * _Nonnull)preset onComplete:(void (^ _Nonnull)(TruvideoSdkCameraResult * _Nonnull))onComplete;
@end


@interface UIViewController (SWIFT_EXTENSION(TruvideoSdkCamera))
/// Presents the AR camera view over the full screen.
/// The camera view is presented <em>modally in full screen</em>, and once the session ends, the result is passed back to the caller.
/// \param preset A <code>TruvideoSdkARCameraConfiguration</code> object containing the AR camera configuration.
///
/// \param onComplete A callback function that receives a <code>TruvideoSdkCameraResult</code> containing captured media.
///
- (void)presentTruvideoSdkARCameraViewWithPreset:(TruvideoSdkARCameraConfiguration * _Nonnull)preset onComplete:(void (^ _Nonnull)(TruvideoSdkCameraResult * _Nonnull))onComplete;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
